name: Build SP530E Binaries

on:
  push:
    branches: [ sp530e-mods ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [ sp530e-mods ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment:
          - sp530e
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          .pio
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Build SP530E firmware
      run: |
        echo "Building for environment: ${{ matrix.environment }}"
        pio run -e ${{ matrix.environment }}
        
    - name: Prepare artifacts
      run: |
        mkdir -p artifacts
        ENV_NAME="${{ matrix.environment }}"
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        
        # Copy firmware binary
        if [ -f ".pio/build/${ENV_NAME}/firmware.bin" ]; then
          cp ".pio/build/${ENV_NAME}/firmware.bin" "artifacts/WLED_SP530E_${ENV_NAME}_${TIMESTAMP}.bin"
        fi
        
        # Copy bootloader and partitions if they exist
        if [ -f ".pio/build/${ENV_NAME}/bootloader.bin" ]; then
          cp ".pio/build/${ENV_NAME}/bootloader.bin" "artifacts/"
        fi
        if [ -f ".pio/build/${ENV_NAME}/partitions.bin" ]; then
          cp ".pio/build/${ENV_NAME}/partitions.bin" "artifacts/"
        fi
        
        # Create info file
        echo "SP530E WLED Build Information" > "artifacts/BUILD_INFO_${ENV_NAME}.txt"
        echo "Environment: ${ENV_NAME}" >> "artifacts/BUILD_INFO_${ENV_NAME}.txt"
        echo "Build Date: $(date)" >> "artifacts/BUILD_INFO_${ENV_NAME}.txt"
        echo "Git Commit: ${GITHUB_SHA}" >> "artifacts/BUILD_INFO_${ENV_NAME}.txt"
        echo "Git Branch: ${GITHUB_REF_NAME}" >> "artifacts/BUILD_INFO_${ENV_NAME}.txt"
        
        ls -la artifacts/
        
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SP530E-${{ matrix.environment }}-${{ github.sha }}
        path: artifacts/
        retention-days: 30
        
    - name: Release binaries
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}