name: Build and Release WLED Main

on:
  push:
    branches: [ main ]
    paths:
      - 'platformio.ini'
      - 'wled00/**'
      - 'usermods/**'
      - 'lib/**'
      - 'include/**'
      - 'tools/**'
      - '.github/workflows/build-main.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install PlatformIO and esptool
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio esptool

    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Build all mainline environments
      run: |
        echo "🔨 Building all mainline environments..."
        pio run --verbose
        echo "Build completed. Checking what was built:"
        ls -la .pio/build/

    # Add additional steps for packaging, release, or artifact upload as needed
